name: build-and-publish-docker

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth, citas, notas, notif]  # Aqu√≠ agregamos todas las im√°genes que necesitas construir
    steps:
      - name: üì• Checkout
        uses: actions/checkout@v4

      - name: üîê Azure Login (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: üîë Login to ACR saludips
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER_saludips }}
          username: ${{ secrets.ACR_USERNAME_saludips }}
          password: ${{ secrets.ACR_PASSWORD_saludips }}

      - name: üè∑Ô∏è Set version tag (short sha)
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: üèóÔ∏è Build & Push auth
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER_saludips }}/auth:latest ./auth
          docker tag ${{ secrets.ACR_LOGIN_SERVER_saludips }}/auth:latest ${{ secrets.ACR_LOGIN_SERVER_saludips }}/auth:${{ steps.vars.outputs.TAG }}
          docker push ${{ secrets.ACR_LOGIN_SERVER_saludips }}/auth:latest
          docker push ${{ secrets.ACR_LOGIN_SERVER_saludips }}/auth:${{ steps.vars.outputs.TAG }}

  build-saludips2:
    runs-on: ubuntu-latest
    steps:
      - name: üì• Checkout
        uses: actions/checkout@v4

      - name: üîê Azure Login (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: üîë Login to ACR saludips2
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER_saludips2 }}
          username: ${{ secrets.ACR_USERNAME_saludips2 }}
          password: ${{ secrets.ACR_PASSWORD_saludips2 }}

      - name: üè∑Ô∏è Set version tag (short sha)
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: üèóÔ∏è Build & Push notif
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER_saludips2 }}/notif:latest ./notif
          docker tag ${{ secrets.ACR_LOGIN_SERVER_saludips2 }}/notif:latest ${{ secrets.ACR_LOGIN_SERVER_saludips2 }}/notif:${{ steps.vars.outputs.TAG }}
          docker push ${{ secrets.ACR_LOGIN_SERVER_saludips2 }}/notif:latest
          docker push ${{ secrets.ACR_LOGIN_SERVER_saludips2 }}/notif:${{ steps.vars.outputs.TAG }}
