name: build-and-publish-docker

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth, citas, notas, notif]  # Servicios a desplegar
        acr: [saludips, saludips2]  # ACRs

    steps:
      - name: üì• Checkout
        uses: actions/checkout@v4

      - name: üîê Azure Login (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: üîë Login to ACR
        uses: azure/docker-login@v1
        with:
          # Selecci√≥n din√°mica de ACR usando 'acr' de la matriz
          login-server: ${{ secrets['ACR_LOGIN_SERVER_' + matrix.acr] }}
          username: ${{ secrets['ACR_USERNAME_' + matrix.acr] }}
          password: ${{ secrets['ACR_PASSWORD_' + matrix.acr] }}

      - name: üè∑Ô∏è Set version tag (short sha)
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: üèóÔ∏è Build & Push ${{ matrix.service }}
        run: |
          docker build -t ${{ secrets['ACR_LOGIN_SERVER_' + matrix.acr] }}/${{ matrix.service }}:latest ./${{ matrix.service }}
          docker tag  ${{ secrets['ACR_LOGIN_SERVER_' + matrix.acr] }}/${{ matrix.service }}:latest ${{ secrets['ACR_LOGIN_SERVER_' + matrix.acr] }}/${{ matrix.service }}:${{ steps.vars.outputs.TAG }}
          docker push ${{ secrets['ACR_LOGIN_SERVER_' + matrix.acr] }}/${{ matrix.service }}:latest
          docker push ${{ secrets['ACR_LOGIN_SERVER_' + matrix.acr] }}/${{ matrix.service }}:${{ steps.vars.outputs.TAG }}
